--- 
knit: "bookdown::render_book"
title: "ESTATÍSTICA COMPUTACIONAL"
subtitle: "Disciplina lecionada para o bacharelado em estatística da UFPB"
author: "**Docente**: Prof. Dr. Pedro Rafael Diniz Marinho <br/> **E-mail**: <pedro.rafael.marinho@gmail.com> / <pedro@de.ufpb.br> <br/> **Perído Letivo**: 2019.1"
site: bookdown::bookdown_site
documentclass: krantz
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
fontsize: 12pt
monofont: "Source Code Pro"
description: "Disciplina de Estatística Computacional - Departamento de Estatística"
---

# {-}

<div class=text-justify>
**Última atualização**: `r data <- function(){
   vec_date <- unlist(strsplit(as.character(Sys.Date()), "-"))
   paste(vec_date[3], vec_date[2], vec_date[1], sep="/")
}; data()` <br/>
**Departamento de Estatística (UFPB)**: <http://www.de.ufpb.br/> 

----

<div style="background-color:rgba(0, 0, 255, 0.2)">
Esse material está sob constante aprimoramento e sugestões poderão ser enviadas para a conta do GitHub que hospeda esse material.
</div>

# Prefácio {-}

<div class=text-justify>
A ementa do curso de **Estatística Computacional** que compõe a estrutura do curso como disciplina obrigatória poderá ser obtida no [link](http://www.de.ufpb.br/graduacao/obrigatorias/EstatisticaComputacional.pdf). Como pode-se observar, a disciplina é dividida no uso de tecnologias (linguagem de marcação e linguagem de programação) e alguns aspectos teóricos que envolvem a teoria da estatística computacional. O bom uso dos conceitos abordados no curso estará alinhado ao perfeito entendimento das tecnologias e teorias apresentadas.
</div>

<div class=text-justify>

<div style="background-color:rgba(0, 0, 255, 0.2)">
O tópico referente à tipografia científica em LaTeX não será abordado, visto que esse assunto atualmente está sendo apresentado na disciplina de Metodologia do Trabalho Científico no início do curso. Além disso, o tópico referente à programação em R abordará aspectos mais avançados da linguagem, uma vez que a essa altura do curso, os alunos entendem os conceitos básicos da linguagem.
