# Prefácio {-}


Esse material sempre tentará se adequar à ementa da disciplina de Estatística Computacional, sendo esta uma disciplina obrigatória do curso de bacharelado em estatística do Departamento de Estatística da UFPB.

A ementa do curso de **Estatística Computacional** que compõe a estrutura do curso como disciplina obrigatória poderá ser obtida no [**link**](http://www.de.ufpb.br/graduacao/obrigatorias/EstatisticaComputacional.pdf). Como pode-se observar, a disciplina é dividida no uso de tecnologias (linguagem de marcação e linguagem de programação) e alguns aspectos teóricos que envolvem a teoria da estatística computacional. O bom uso dos conceitos abordados no curso estará alinhado ao perfeito entendimento das tecnologias e teorias apresentadas.


<div style="background-color:rgba(255, 165, 0, 0.65)">
O tópico referente à tipografia científica em [**LaTeX**](https://www.latex-project.org/) não será abordado, visto que esse assunto atualmente está sendo apresentado na disciplina de Metodologia do Trabalho Científico no início do curso. Além disso, o tópico referente à programação em [**R**](https://www.r-project.org/) abordará aspectos mais avançados da linguagem, uma vez que a essa altura do curso, os alunos entendem os conceitos básicos da linguagem [**R**](https://www.r-project.org/).
</div>

**Tecnologias**

1. Programação em linguagem R;

2. Linguagem de marcação LaTeX.




**Teorias**